version: "3.2"
services:
  vtiger:
    image: pimuzzo/vtiger
    container_name: vtiger
    environment:
      DB_HOSTNAME: mysql
      DB_USERNAME: vtiger
      DB_PASSWORD: vtiger@01
      DB_NAME: vtiger
    ports: 
      - "80:80"
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7.13
    container_name: vtiger_database
    environment: 
      MYSQL_ROOT_PASSWORD: password@01 # TODO: Change this
      MYSQL_USER: vtiger
      MYSQL_PASSWORD: vtiger@01
      MYSQL_DATABASE: vtiger
    command: "--innodb_use_native_aio=0"
    volumes:
      - ./database:/var/lib/mysql